repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  # note: pre-commit runs top-to-bottom, so put the hooks that modify content first,
  # followed by checks that might be more likely to pass after the modifactaion hooks (like flake8)
  hooks:
  # Checks for large files added to the repository, typically to prevent accidental inclusion of large binaries or datasets.
  - id: check-added-large-files
  # Detects potential filename conflicts due to case-insensitive filesystems (e.g., Windows) where File.txt and file.txt would be considered the same.
  - id: check-case-conflict
  # Checks for files that contain merge conflict strings (e.g., <<<<<<<, =======, >>>>>>>).
  - id: check-merge-conflict
  # Validates YAML files for syntax errors.
  - id: check-yaml
  # Ensures files have a newline at the end.
  - id: end-of-file-fixer
  # Removes trailing whitespace characters from files.
  - id: trailing-whitespace

- repo: local
  hooks:
    - id: check-assets
      name: check assets
      language: python
      entry: scripts/osf_files.py check-assets all
      always_run: true
      pass_filenames: false
      additional_dependencies: ["requests", "click", "tqdm"]
