[project]
name = "plenoptic-presentations"
version = "0.1.0"
description = "python package to handle upload/download assets for presentations"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.3.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
